### ISSUE TITLE
Can't see the swagger ui

### ISSUE THREAD

**Issue by seekheart** [swege/flask-restful-swagger-2.0#22]
I tried running my api (flask_restful) with the following code and I couldn't get the swagger ui to show.

```
# Bootstrap api and engines
app = flask.Flask('__name__')
api = flask_restful_swagger_2.Api(app)
```

I get a 404 not found and I'm on python 3.6 and latest stable flask

**Comment by H0schi** [comment]
Have you tried accessing the URL with a trailing `.html `or `.json,` i.e. `"localhost:5000/api/swagger.html"`?

**Comment by swege** [comment]
The html frontend is not included in this project. Therefore, you can just access `http://localhost:5000/api/swagger.json`. You may download a swagger ui separately or use this online version: http://petstore.swagger.io/?url=http://localhost:5000/api/swagger.json

**Comment by apocalypse2012** [comment]
Swagger petstore appears to no longer be compatible...
127.0.0.1 - - [22/May/2019 16:37:38] code 400, message Bad request version ('\x80þ\x7fÈÝ¬R`EÛÆ,\x89\x00"jj\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [22/May/2019 16:37:38] "üÝÂÿ¶VÆÛÊ/t¯´ÕÜ ¤ØÖ?@¿~Ñ CT®\ß^¶×±rVhgþÈÝ¬R`EÛÆ,"jjÀ+À/À,À0Ì©Ì¨ÀÀ/5[0m" HTTPStatus.BAD_REQUEST -
127.0.0.1 - - [22/May/2019 16:37:38] code 400, message Bad request version ('JJÀ+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [22/May/2019 16:37:38] "Ã¿·Í?"ýp ®±ÂIiºPëã§T°Äü,:`JJÀ+À/À,À0Ì©Ì¨ÀÀ/5" HTTPStatus.BAD_REQUEST -

**Comment by Uzzije** [comment]
Not sure if this is still relevant, but downloading flask_swagger_ui did the trick for me. Set the API_URL parameter in flask_swagger_ui's  `get_swaggerui_blueprint` function to the url path of the json file created from using flask_restful_swagger_2. That path for me was http://localhost:5000/api/swagger.json

E.g, add these two lines to your swagger setup code.
   ` app.register_blueprint(get_swagger_blueprint(docs, 
                '/api/swagger', title='Api Name',
                                                         api_version='1'))` As seen in  flask_restful_swagger_2 examples

`app.register_blueprint(get_swaggerui_blueprint('/api/docs',
                                                           http://localhost:5000/api/swagger.json,
                                                           config={
                                                               'app_name': "Api Name"
                                                           }), url_prefix='/api/docs') `
You can see the full code example in the swagger_ui readme example => https://github.com/sveint/flask-swagger-ui/blob/master/README.md
